// // GENERATED BY server/framesCodegen.ts
// import i1c from './frames/ezequiel.svelte';
// import i1m from './frames/ezequiel.meta.json';
// import i2c from './frames/links.svelte';
// import i2m from './frames/links.meta.json';
// import i3c from './frames/news-letter.svelte';
// import i3m from './frames/news-letter.meta.json';

// const framesComponents = {
//   "ezequiel": { Component: i1c, meta: i1m },
//   "links": { Component: i2c, meta: i2m },
//   "news-letter": { Component: i3c, meta: i3m },
// };
// export default framesComponents;
